pipeline{
  agent any
  stages{
    stage("Build){
          steps{
            echo"Build Happpens Here"
          }
    }
    stage("Deploy"){
      steps{
        echo"Deploy Happens Here"
      }
    }
  }
}
